# -*- coding: utf-8 -*-
"""analise_exploratoria_imoveis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X5DrNlu8N9obIh6D-5LJOaBPU8DmatDu

# Conhecendo a base de dados

## Importando os dados
"""

import pandas as pd

url = 'https://raw.githubusercontent.com/alura-cursos/pandas-conhecendo-a-biblioteca/main/base-de-dados/aluguel.csv'
pd.read_csv(url)

pd.read_csv(url, sep=';')

dados = pd.read_csv(url, sep=';')
dados

dados.head()

dados.tail()

type(dados)

"""## Características gerais da base de dados"""

dados.shape

dados.columns

dados.info()

dados['Tipo']

dados[['Quartos','Valor']]

"""# Análise exploratória de dados

## Qual o valor médio de aluguel por tipo de imóvel?
"""

dados.head()

dados['Valor'].mean()

dados.groupby('Tipo').mean(numeric_only=True)

dados.groupby('Tipo')['Valor'].mean()

dados.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

df_preco_tipo = dados.groupby('Tipo')[['Valor']].mean().sort_values('Valor')

df_preco_tipo.plot(kind='barh', figsize=(14, 10), color = 'pink');

"""## Removendo os imóveis comerciais"""

dados.Tipo.unique()

imoveis_comerciais = ['Conjunto Comercial/Sala',
                      'Prédio Inteiro', 'Loja/Salão',
                      'Galpão/Depósito/Armazém',
                      'Casa Comercial', 'Terreno Padrão',
                      'Loja Shopping/ Ct Comercial',
                      'Box/Garagem', 'Chácara',
                      'Loteamento/Condomínio', 'Sítio',
                      'Pousada/Chalé', 'Hotel', 'Indústria']

dados.query('@imoveis_comerciais in Tipo')

dados.query('@imoveis_comerciais not in Tipo')

df = dados.query('@imoveis_comerciais not in Tipo')
df

df.Tipo.unique()

df_preco_tipo = df.groupby("Tipo")[["Valor"]].mean().sort_values("Valor")

df_preco_tipo.plot(kind='barh', figsize=(14, 10), color ='pink');

"""## Qual o percentual de cada tipo de imóvel na nossa base de dados?"""

df.Tipo.unique()

df.Tipo.value_counts(normalize=True)

df.Tipo.value_counts(normalize=True).to_frame().sort_values('Tipo')

df_percentual_tipo = df.Tipo.value_counts(normalize=True).to_frame().sort_values('Tipo')

df_percentual_tipo.plot(kind='bar', figsize=(14, 10), color ='pink',
                          xlabel='Tipo', ylabel='Percentual');



"""### **Selecionando apenas os imóveis do tipo apartamento**"""

df.query('Tipo == "Apartamento"')

df = df.query('Tipo == "Apartamento"')
df.head()

"""# Tratando e filtrando os dados

## Lidando com dados nulos
"""













"""## Removendo registros"""



















"""## Filtros

### **1. Apartamentos que possuem `1 quarto` e `aluguel menor que 1200`**
"""











"""### **2. `Apartamentos` que possuem pelo menos `2 quartos`, `aluguel menor que 3000` e `area maior que 70`**"""





"""## Salvando os dados"""

















"""# Manipulando os dados

## Criando colunas numéricas
"""







"""## Criando colunas categóricas"""









